// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

#pragma once

#include "MainWindow.g.h"

namespace winrt::NativeApp::implementation
{
    struct MainWindow : MainWindowT<MainWindow>
    {
        MainWindow();

        void btnInitializeDotNet_Click(Windows::Foundation::IInspectable const& sender, Microsoft::UI::Xaml::RoutedEventArgs const& args);
        void btnCsWinRtLauncher_Click(Windows::Foundation::IInspectable const& sender, Microsoft::UI::Xaml::RoutedEventArgs const& args);

    private:
        winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider m_metadataProvider{ nullptr };

        /// <summary>
        /// Returns the IXamlMetadataProvider generated by the <seealso cref="CsWinRtComponent"/> XAML code.
        /// </summary>
        /// <remarks>
        /// By deferring the creating of this object until runtime, we can reduce the startup time of the launching application.
        /// </remarks>
        /// <returns>
        /// Metadata provider that can be registerd with the XAML runtime
        /// </returns>
        winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider MainWindow::GetXamlMetadataProvider();

        void OpenDialog();
    };
}

namespace winrt::NativeApp::factory_implementation
{
    struct MainWindow : MainWindowT<MainWindow, implementation::MainWindow>
    {
    };
}
