namespace Playground.Controls
{
    [default_interface]
    runtimeclass SwapChainPanelControl : Microsoft.UI.Xaml.Controls.Control
    {
        SwapChainPanelControl();
        Int32 MyProperty;
    }
}
