// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace WinRtComponent
{
    [default_interface]
    runtimeclass MyWinRtClass : Microsoft.UI.Xaml.Interop.INotifyCollectionChanged
    {
        MyWinRtClass();

        void TestCollection();

        Int32 MyLuckyNumber{ get; set; };
    }
}
