// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "ComProxyData.idl";

namespace IpcApp
{
	[default_interface]
	runtimeclass ComProxyServer
	{
		ComProxyServer();

		void MarshalData(IpcApp.ComProxyData data);
		void UnmarshalData();
	}
}